map_area_x = 10  # x좌표 맵 블럭 개수
map_area_y = 5  # y좌표 맵 블럭 개수
map_area_size_x = 1000  # 맵 블럭 하나당 크기
map_area_size_y = 1000
player = None
start_point=None
player_start_x = 0  # 플레이어 시작 좌표
player_start_y = 0
player_area_x = 0  # 플레이어가 있는 맵 블럭
player_area_y = 0
missile = None
cx = 0  # 카메라 좌표
cy = 0
block = []
block_sleep = []
monster = []
monster_sleep = []
background = []
background_sleep = []
ui = None
